export const gameProgress = {
  GAME_BEFORE_START: "GAME_BEFORE_START",
  GAME_ALL_PLAYER_READY: "GAME_ALL_PLAYER_READY",
  GAME_START: "GAME_START",
  GAME_OVER: "GAME_OVER",
  GAME_RESTART: "GAME_RESTART",
  GAME_CLEAR: "GAME_CLEAR",
};
