export const gameProgress = {
  GAME_BEFORE_START: "GAME_BEFORE_START",
  GAME_ALL_PLAYER_READY: "GAME_ALL_PLAYER_READY",
  GAME_START: "GAME_START",
  GAME_RESET: "GAME_RESET",
  GAME_CLEAR: "GAME_CLEAR",
  GAME_OVER: "GAME_OVER",
  GAME_WIN: "GAME_WIN",
  GAME_LOSE: "GAME_LOSE",
};
